### ISSUE TITLE
Assign Student Component Modularity

### ISSUE THREAD

**Issue by kimhnguyenn** [JumboCode/TheLegacyProject2#122]
Problem
When viewing a senior's profile, there is a description and a list of students that are assigned to the senior. In addition to that, there is a button that allows the chapter leader to assign student(s) to that senior. A similar UI and functionality exists for a member's profile. For a member's profile, there is a description and a list of seniors that are assigned to the member. In addition to that, there is a button that allows the chapter leader to assign senior(s) to the member. Make the button from the senior's profile page modular, such that it can be used in the member's profile page but for assigning seniors instead.

**Comment by nickbar01234** [comment]
Duplicated of #123.
