### ISSUE TITLE
Rewrite the UI to render the popup when adding a new senior to the database

### ISSUE THREAD

**Issue by kimhnguyenn** [JumboCode/TheLegacyProject2#18]
## Problem

There are some UI/UX problems with the current popup when a user adds a senior.

![image](https://github.com/JumboCode/TheLegacyProject2/assets/74647679/3d9904e2-3fcc-4c1a-afd7-daef3193d987)

## Specifications

Your task is to revamp the looks / feel of the popup according to the Figma design.

![image](https://github.com/JumboCode/TheLegacyProject2/assets/74647679/7e34c7de-9196-47c6-bbef-b2918c285f55)

You will only implement the frontend in this task. **Don't worry** about plugging in the backend code to make a senior; we will take care of that in future sprints. Once you're finished with your implementation, you can mark the previous component as `@deprecated` and swap in your implementation.

## Pointers

1. We currently don't have the mock-ups for the pop-up when we edit seniors yet. But we expect that the UI will be similar. Therefore, your implementation should account for that.
2. The current implementation for the popup is found in `./src/components/AddSenior.tsx`. You have the option to modify the existing file or create a new one. You may find it easier to create a new file and use the old one for Tailwind references.

**Comment by selenaz03** [comment]
Subtasks:

- concatenate first and last name "seniorData.name" ->populate that
- fix button colors
- fix hover on student list
- allow deletion of students added
